### PR TITLE
Bugfix Deposit/Withdraw button placement

### LINKED ISSUE #35: BUG: Deposit/Withdraw button spacing wonky on different screens
### User Story
As a USER I want the spacing of inline buttons (EG: Deposit Withdraw) to look good and centered across multiple devices with both slightly and wildly different screens

### Context / Additional Information
For Example: When @theanticrumpet opens the app on a Pixel 3 emu the deposit and withdraw buttons appear offset compared to @jleeboyd on Pixel 3a XL and whatever @StopMakingUsernamesUnique is using

Apparently using density independent pixels is pretty good, but not always perfect.

image

### Acceptance Criteria
- [x] Buttons are centered

### PR DESCRIPTION
**Pull request by Dylan-Riley**
Resolves https://github.com/jleeboyd/family-bank-app/issues/35

Removes old style of margin-ing for deposit and withdraw buttons and places them inside a nested linearlayout with potentially fixed margining. Now appears centered on my emu, please checkout branch and check your own emu to make sure it works across multiple devices

image

### CODE REVIEW

**Comment by Dylan-Riley** [comment]
I should note I was sure to check back out to master then branch off that for this PR. This does not include any changes found in JB-test-branch

**Review by jleeboyd — APPROVED** [review]
New UI looks good, thanks for including a screenshot as well.

**Comment by Dylan-Riley** [comment]
Used web view to resolve merge conflict (new delete transaction button not included yet)

**Comment by Dylan-Riley** [comment]
Closed 'cause I'll just recreate this in the current visual bugfixes I'm doing

**Pull request closed without merging**
